In [2]:
import numpy as np

In [3]:
demo=[10,20,30]
np.array(demo)

array([10, 20, 30])

In [4]:
d2=[10,20,'xyz']
np.array(d2)

array(['10', '20', 'xyz'], dtype='<U21')

In [7]:
g=np.zeros(5,int)
k= np.ones(5)
print(k)
print(g)
k.dtype

[1. 1. 1. 1. 1.]
[0 0 0 0 0]


dtype('float64')

In [7]:
import numpy as np
new_array = np.zeros((3,4,5))
print(new_array)

new_array[0][1][2]

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


0.0

In [8]:
twod_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twod_array[1:3])

print(twod_array[:,1])

print(twod_array[1:3,0])

print(twod_array[1:3,0:2])

[[4 5 6]
 [7 8 9]]
[2 5 8]
[4 7]
[[4 5]
 [7 8]]


In [9]:
x=np.array([1,2,3])
y=np.array([3,5,6])
x=x+10
print(x)
print(x+y)
print(x*2)
print(x*y)
print(x.mean())
print(x.sum())

[11 12 13]
[14 17 19]
[22 24 26]
[33 60 78]
12.0
36


In [10]:
p1=np.array([2,2,2])
p2=np.array([1,1,1])
val=((p1-p2)**2).sum()
print(val)
np.sqrt(val)

3


1.7320508075688772

In [11]:
pts=np.array([4,5,6,7])
val1=((pts-pts.mean())**2).sum()
print(val1)
np.sqrt(val1)

5.0


2.23606797749979